import React,{useEffect,useMemo,useState}from"react";
import{createRoot}from"react-dom/client";
import"./style.css";
const API=(import.meta.env.VITE_API_URL||"").replace(/\/$/,"");
function App(){
const[videos,setVideos]=useState([]),[q,setQ]=useState(""),[modal,setModal]=useState(false),[editing,setEditing]=useState(null),[file,setFile]=useState(null),[msg,setMsg]=useState(""),[progress,setProgress]=useState(0);
const[form,setForm]=useState({titulo:"",descripcion:"",vistas:0,likes:0,estado:"activo",fijado:false,posicion:""});
async function load(){if(!API){setMsg("Falta configurar VITE_API_URL en Vercel.");return}try{const r=await fetch(API+"/api/videos");if(!r.ok)throw new Error();const d=await r.json();setVideos(d.videos||[]);setMsg("")}catch{setMsg("No se pudo conectar con la API del VPS.")}}
useEffect(()=>{load()},[]);
const list=useMemo(()=>videos.filter(v=>(v.titulo+" "+(v.descripcion||"")).toLowerCase().includes(q.toLowerCase())),[videos,q]);
function add(){setEditing(null);setFile(null);setProgress(0);setMsg("");setForm({titulo:"",descripcion:"",vistas:0,likes:0,estado:"activo",fijado:false,posicion:""});setModal(true)}
function edit(v){setEditing(v);setFile(null);setProgress(0);setMsg("");setForm({titulo:v.titulo||"",descripcion:v.descripcion||"",vistas:v.vistas||0,likes:v.likes||0,estado:v.estado||"activo",fijado:!!v.fijado,posicion:v.posicion??""});setModal(true)}
async function save(e){e.preventDefault();if(editing){const r=await fetch(API+"/api/videos/"+editing._id,{method:"PUT",headers:{"Content-Type":"application/json"},body:JSON.stringify({...form,vistas:Number(form.vistas)||0,likes:Number(form.likes)||0,posicion:form.fijado&&form.posicion!==""?Number(form.posicion):null})});const d=await r.json();if(d.success){setModal(false);load()}else setMsg(d.message||"No se pudo guardar");return}
if(!file){setMsg("Selecciona un video.");return}
const fd=new FormData();fd.append("video",file);Object.entries({...form,vistas:Number(form.vistas)||0,likes:Number(form.likes)||0,posicion:form.fijado?form.posicion:""}).forEach(([k,v])=>fd.append(k,String(v)));
const x=new XMLHttpRequest();x.open("POST",API+"/api/videos");x.upload.onprogress=e=>{if(e.lengthComputable)setProgress(Math.round(e.loaded/e.total*100))};x.onload=()=>{try{const d=JSON.parse(x.responseText);if(d.success){setModal(false);load()}else setMsg(d.message||"Error al subir")}catch{setMsg("Respuesta inválida")}};x.onerror=()=>setMsg("No se pudo conectar con el VPS.");x.send(fd)}
async function remove(v){if(!confirm(`¿Eliminar "${v.titulo}"?`))return;const r=await fetch(API+"/api/videos/"+v._id,{method:"DELETE"});const d=await r.json();if(d.success)load();else alert(d.message||"No se pudo eliminar")}
const fmt=n=>n>=1e6?(n/1e6).toFixed(1).replace(".0","")+"M":n>=1e3?(n/1e3).toFixed(1).replace(".0","")+"k":String(n||0);
return <main className="page"><header className="top"><div><h1>Videos <span>{videos.length}</span></h1><p>Sube y administra tus videos del VPS.</p></div><div className="tools"><input placeholder="Buscar" value={q} onChange={e=>setQ(e.target.value)}/><button className="primary" onClick={add}>+ Nuevo</button></div></header>{msg&&<div className="notice">{msg}</div>}<section className="table"><div className="row head"><div>Video</div><div>Título / descripción</div><div>Vistas / Likes</div><div>Fijado</div><div>Estado</div><div>Acciones</div></div>{list.map(v=><div className="row" key={v._id}><div><video className="thumb" controls preload="metadata" src={v.url}/></div><div><strong>{v.titulo}</strong><small>{v.descripcion||"Sin descripción"}</small><code>{v.url}</code></div><div className="stats"><span>👁 {fmt(v.vistas)} vistas</span><span>♡ {fmt(v.likes)}</span></div><div>{v.fijado?`📌 ${v.posicion}`:"—"}</div><div><span className={"badge "+v.estado}>{v.estado}</span></div><div className="actions"><button onClick={()=>navigator.clipboard.writeText(v.url)}>Copiar URL</button><button onClick={()=>edit(v)}>Editar</button><button className="danger" onClick={()=>remove(v)}>Eliminar</button></div></div>)}</section>{modal&&<div className="overlay"><div className="modal"><div className="modalTitle"><h2>{editing?"Editar video":"Nuevo video"}</h2><button onClick={()=>setModal(false)}>✕</button></div><form onSubmit={save}>{!editing&&<label>Archivo<input type="file" accept="video/*" onChange={e=>setFile(e.target.files[0])}/></label>}<label>Título<input required value={form.titulo} onChange={e=>setForm({...form,titulo:e.target.value})}/></label><label>Descripción<textarea rows="4" value={form.descripcion} onChange={e=>setForm({...form,descripcion:e.target.value})}/></label><div className="cols"><label>Vistas<input type="number" min="0" value={form.vistas} onChange={e=>setForm({...form,vistas:e.target.value})}/></label><label>Likes<input type="number" min="0" value={form.likes} onChange={e=>setForm({...form,likes:e.target.value})}/></label></div><div className="cols"><label>Estado<select value={form.estado} onChange={e=>setForm({...form,estado:e.target.value})}><option value="activo">Activo</option><option value="inactivo">Inactivo</option></select></label><label>Posición<input type="number" min="1" disabled={!form.fijado} value={form.posicion} onChange={e=>setForm({...form,posicion:e.target.value})}/></label></div><label className="check"><input type="checkbox" checked={form.fijado} onChange={e=>setForm({...form,fijado:e.target.checked,posicion:e.target.checked?form.posicion:""})}/> Fijar video</label>{progress>0&&<progress max="100" value={progress}/>}<div className="modalActions"><button type="button" onClick={()=>setModal(false)}>Cancelar</button><button className="primary">{editing?"Guardar cambios":"Subir video"}</button></div></form></div></div>}</main>}
createRoot(document.getElementById("root")).render(<App/>);